backend:
  image:
    repository: phucnotphuc/yas-recommendation
    tag: latest
  ingress:
    enabled: true
    host: api-dev.yas.local.com
    path: /recommendation
  serviceMonitor:
    enabled: false

